# Generated by Django 5.0.6 on 2024-09-17 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('contract_address', models.CharField(max_length=255, unique=True)),
                ('decimals', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_address', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tx_hash', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodeck.token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodeck.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='TokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('date_fetched', models.DateTimeField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodeck.token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodeck.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='TokenAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=255)),
                ('allowance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodeck.token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodeck.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('date', models.DateField()),
                ('fetched_at', models.DateTimeField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodeck.token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodeck.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodeck.token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodeck.wallet')),
            ],
        ),
    ]
